


import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paula
 */
public class altaVehiculos extends javax.swing.JFrame {

    /**
     * Creates new form altaVehiculos
     */
    public altaVehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoVehiculoLabel = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        MatriculaLabel = new javax.swing.JLabel();
        matriculaTF = new javax.swing.JTextField();
        marcaLabel = new javax.swing.JLabel();
        marcaTF = new javax.swing.JTextField();
        ModeloLabel = new javax.swing.JLabel();
        modeloTF = new javax.swing.JTextField();
        PotenciaLabel = new javax.swing.JLabel();
        potenciaTF = new javax.swing.JTextField();
        ColorLabel = new javax.swing.JLabel();
        colorTF = new javax.swing.JTextField();
        MatriculacionLabel = new javax.swing.JLabel();
        matriculacionTF = new javax.swing.JTextField();
        KMLabel = new javax.swing.JLabel();
        KMTF = new javax.swing.JTextField();
        PrecioLabel = new javax.swing.JLabel();
        precioTF = new javax.swing.JTextField();
        TipoMotoLabel = new javax.swing.JLabel();
        cilandraLabel = new javax.swing.JLabel();
        combustibleLabel = new javax.swing.JLabel();
        cambioLabel = new javax.swing.JLabel();
        plazasLabel = new javax.swing.JLabel();
        tipoAutomovilLabel = new javax.swing.JLabel();
        tipoAutoComboBox = new javax.swing.JComboBox<>();
        puertasLabel = new javax.swing.JLabel();
        traccionLabel = new javax.swing.JLabel();
        tipoMotoTF = new javax.swing.JTextField();
        cilandraTF = new javax.swing.JTextField();
        combustibleTF = new javax.swing.JTextField();
        cambioTF = new javax.swing.JTextField();
        plazasTF = new javax.swing.JTextField();
        puertasTF = new javax.swing.JTextField();
        traccionTF = new javax.swing.JTextField();
        registrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipoVehiculoLabel.setText("Tipo vehiculo:");

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motocicleta", "Automovil" }));

        MatriculaLabel.setText("Matricula:");

        matriculaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaTFActionPerformed(evt);
            }
        });

        marcaLabel.setText("Marca");

        ModeloLabel.setText("Modelo");

        modeloTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloTFActionPerformed(evt);
            }
        });

        PotenciaLabel.setText("Potencia");

        potenciaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaTFActionPerformed(evt);
            }
        });

        ColorLabel.setText("Color");

        MatriculacionLabel.setText("Fecha matriculacion");

        KMLabel.setText("Kilometros");

        PrecioLabel.setText("Precio");

        TipoMotoLabel.setText("Tipo (Motocicleta)");

        cilandraLabel.setText("Cilandra (Motocicleta)");

        combustibleLabel.setText("Combustible (Automovil)");

        cambioLabel.setText("Cambio (Automovil)");

        plazasLabel.setText("Numero de plazas (Automovil)");

        tipoAutomovilLabel.setText("tipo de automovil");

        tipoAutoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turismo", "Todoterreno" }));
        tipoAutoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAutoComboBoxActionPerformed(evt);
            }
        });

        puertasLabel.setText("Numero de puertas (Turimo)");

        traccionLabel.setText("Traccion (Todoterreno)");

        puertasTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertasTFActionPerformed(evt);
            }
        });

        registrarButton.setText("Registrar");
        registrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(traccionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(puertasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoAutomovilLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plazasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(cambioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combustibleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cilandraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TipoMotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrecioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MatriculacionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ColorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PotenciaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModeloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoVehiculoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MatriculaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tipoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(matriculaTF)
                        .addComponent(marcaTF)
                        .addComponent(modeloTF)
                        .addComponent(potenciaTF)
                        .addComponent(colorTF)
                        .addComponent(matriculacionTF)
                        .addComponent(KMTF)
                        .addComponent(precioTF)
                        .addComponent(tipoAutoComboBox, 0, 112, Short.MAX_VALUE)
                        .addComponent(tipoMotoTF)
                        .addComponent(cilandraTF)
                        .addComponent(combustibleTF)
                        .addComponent(cambioTF)
                        .addComponent(plazasTF)
                        .addComponent(puertasTF)
                        .addComponent(traccionTF)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoVehiculoLabel)
                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MatriculaLabel)
                    .addComponent(matriculaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcaLabel)
                    .addComponent(marcaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeloLabel)
                    .addComponent(modeloTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PotenciaLabel)
                    .addComponent(potenciaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ColorLabel)
                    .addComponent(colorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MatriculacionLabel)
                    .addComponent(matriculacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KMLabel)
                    .addComponent(KMTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrecioLabel)
                    .addComponent(precioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TipoMotoLabel)
                    .addComponent(tipoMotoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cilandraLabel)
                    .addComponent(cilandraTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combustibleLabel)
                    .addComponent(combustibleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambioLabel)
                    .addComponent(cambioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plazasLabel)
                    .addComponent(plazasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoAutomovilLabel)
                    .addComponent(tipoAutoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puertasLabel)
                    .addComponent(puertasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(traccionLabel)
                    .addComponent(traccionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registrarButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matriculaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaTFActionPerformed

    private void modeloTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTFActionPerformed

    private void potenciaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potenciaTFActionPerformed

    private void puertasTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertasTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertasTFActionPerformed

    private void registrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarButtonMouseClicked
        Vehiculos vehiculo = new Vehiculos();
        int cont=10;
        String tipoVehiculo= (String) tipoComboBox.getSelectedItem();
        String matricula= matriculaTF.getText();
        String marca= marcaTF.getText();
        String modelo= modeloTF.getText();
        String potencia= potenciaTF.getText();
        String color= colorTF.getText();
        String matriculacion = matriculacionTF.getText();
        String km = KMTF.getText();
        String precio = precioTF.getText();
        
        vehiculo.getVehiculosLista().get(cont).add(0, tipoVehiculo);
        vehiculo.getVehiculosLista().get(cont).add(1, matricula);
        vehiculo.getVehiculosLista().get(cont).add(2, marca);
        vehiculo.getVehiculosLista().get(cont).add(3, modelo);
        vehiculo.getVehiculosLista().get(cont).add(4, potencia);
        vehiculo.getVehiculosLista().get(cont).add(5, color);
        vehiculo.getVehiculosLista().get(cont).add(6, matriculacion);
        vehiculo.getVehiculosLista().get(cont).add(7, km);
        vehiculo.getVehiculosLista().get(cont).add(8, precio);
        
        if (tipoVehiculo.equals("Automovil")){
            String combustible= combustibleTF.getText();
            String cambio= cambioTF.getText();
            String plazas= plazasTF.getText();
            vehiculo.getVehiculosLista().get(cont).add(9, combustible);
            vehiculo.getVehiculosLista().get(cont).add(10, cambio);
            vehiculo.getVehiculosLista().get(cont).add(11, plazas);
            if (tipoAutoComboBox.getSelectedItem().equals("Turismo")){
                 String puertas= puertasTF.getText();
                vehiculo.getVehiculosLista().get(cont).add(12, puertas);
                ++ cont;
            }
            else{
                String traccion=traccionTF.getText();
                vehiculo.getVehiculosLista().get(cont).add(12, traccion);
                ++cont;
            }   
        }
        else{
            String tipoMoto = tipoMotoTF.getText();
            String cilandra= cilandraTF.getText();
            vehiculo.getVehiculosLista().get(cont).add(9, tipoMoto);
            vehiculo.getVehiculosLista().get(cont).add(10, cilandra);
            ++ cont;
            
        }
    }//GEN-LAST:event_registrarButtonMouseClicked

    private void tipoAutoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAutoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAutoComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColorLabel;
    private javax.swing.JLabel KMLabel;
    private javax.swing.JTextField KMTF;
    private javax.swing.JLabel MatriculaLabel;
    private javax.swing.JLabel MatriculacionLabel;
    private javax.swing.JLabel ModeloLabel;
    private javax.swing.JLabel PotenciaLabel;
    private javax.swing.JLabel PrecioLabel;
    private javax.swing.JLabel TipoMotoLabel;
    private javax.swing.JLabel cambioLabel;
    private javax.swing.JTextField cambioTF;
    private javax.swing.JLabel cilandraLabel;
    private javax.swing.JTextField cilandraTF;
    private javax.swing.JTextField colorTF;
    private javax.swing.JLabel combustibleLabel;
    private javax.swing.JTextField combustibleTF;
    private javax.swing.JLabel marcaLabel;
    private javax.swing.JTextField marcaTF;
    private javax.swing.JTextField matriculaTF;
    private javax.swing.JTextField matriculacionTF;
    private javax.swing.JTextField modeloTF;
    private javax.swing.JLabel plazasLabel;
    private javax.swing.JTextField plazasTF;
    private javax.swing.JTextField potenciaTF;
    private javax.swing.JTextField precioTF;
    private javax.swing.JLabel puertasLabel;
    private javax.swing.JTextField puertasTF;
    private javax.swing.JButton registrarButton;
    private javax.swing.JComboBox<String> tipoAutoComboBox;
    private javax.swing.JLabel tipoAutomovilLabel;
    private javax.swing.JComboBox<String> tipoComboBox;
    private javax.swing.JTextField tipoMotoTF;
    private javax.swing.JLabel tipoVehiculoLabel;
    private javax.swing.JLabel traccionLabel;
    private javax.swing.JTextField traccionTF;
    // End of variables declaration//GEN-END:variables
}
