
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paula
 */
public class visualizarVehiculos extends javax.swing.JFrame {
        marcaModelo marcaModelo= new marcaModelo();
         
        String txt = "";
    /**
     * Creates new form visualizarVehiculos
     */
    public visualizarVehiculos() {
        initComponents();
        
        dibujaVehiculos(txt);
        
    }
       
    
    public void dibujaVehiculos(String texto) {
         String nombreImagen = "";
         
         
        
        switch (txt){
            case "500C" : nombreImagen = "/images/500CV.jpg"; break;
            case "500": nombreImagen = "/images/500.jpg"; break;
            case "HP4 Race" : nombreImagen = "/images/HP4Race.jpg"; break;
            case "Land cruiser": nombreImagen = "/images/Landcruiser.jpg"; break;
            case "Picanto" : nombreImagen = "/images/Picanto.jpg"; break;
            case "RAV 4" : nombreImagen = "/images/RAV4.jpg"; break;
            case "Rio" : nombreImagen = "/images/Rio.jpg"; break;
            case "S 100 RR" : nombreImagen = "/images/S100RR.jpg"; break;
            case "Super sport": nombreImagen="/images/superSport.jpg";break;
            case "Sport touring": nombreImagen="/images/sportTouring.jpg";break;
            default : nombreImagen = "/images/sportTouring.jpg"; break;
        }
        
        ImageIcon miImagen =
                new ImageIcon(
                    new ImageIcon(getClass().getResource(nombreImagen))
                        .getImage()
                        .getScaledInstance(visorImagen.getWidth(),
                                           visorImagen.getHeight(),
                                           Image.SCALE_DEFAULT)
                );
        visorImagen.setIcon(miImagen);
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visorImagen = new javax.swing.JLabel();
        CerrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CerrarButton.setText("Cerrar");
        CerrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(visorImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(CerrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(visorImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CerrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarButtonMouseClicked
       marcaModelo marcaModelo = new marcaModelo ();
       marcaModelo.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_CerrarButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualizarVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarButton;
    private javax.swing.JLabel visorImagen;
    // End of variables declaration//GEN-END:variables

   
}
